Iter5
alexander-m-utkin/go-shortener pull request #5
Opened 2024-08-17 11:56 UTC by alexander-m-utkin

2024-08-19 09:08 UTC, Bazys requested changes
из майн, всю логику в интернал

2024-08-22 09:41 UTC, nburunova requested changes

2024-08-22 09:41 UTC, nburunova commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
Почему ты хочешь защититься от нескольких вызовов Init()? Что сломается, если несколько раз вызвать Init()?

2024-08-22 09:41 UTC, nburunova commented on internal/pkg/config/config.go
> +			log.Fatal(err)
лучше тут не делать fatal, а возвращать ошибку. И эту ошибку обрабатывать уровнем выше, у тебя это main. Потому что на уровне этого метода, ты не знаешь, фатальная это ошибка или нет. Если пофантазировать, вдруг у main есть другие способы настроить конфиг? или начать работу без конфига?

Panic, fatal лучше вообще не использовать, или использовать на уровне функции main.

2024-08-22 10:14 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
Это чтобы соблюсти подход Singleton - скорее не чтобы защититься, а чтобы если его много раз вызывает кто-то, то он не отрабатывал каждый раз (создавал конфиг), а переисползовал уже существующий конфиг. 
Стоит переделать ?

2024-08-22 10:26 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
да, тесты могут например перезапускать  init

2024-08-22 10:40 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
да, если убрать проверку if !c.isInitiated , и запустить все тесты, то они падают, т.к. они запускают init, в котором повторно запускается flag.Parse() , что приводит к падению.

2024-08-22 10:41 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +			log.Fatal(err)
испарвил, вынес в main.

2024-08-22 13:01 UTC, nburunova commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
для случаев, когда что-то нужно сделать единожды, используется sync.Once. Однако тема sync будет только в 5 спринте. 
Можно пойти двумя путами:
- оставить реализацию с bool.
- спарсить flags в main, она-то точно запускается 1 раз, и передать значения флагов в Init в качестве аргументов

2024-08-22 15:03 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
сделал второй вариант, через main, но сам исполняемый код flag.Parse() оставил в config.go в отдельной функции, которая вызывается из main.

2024-08-23 07:09 UTC, nburunova commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
у тебя теперь Configuration.ParseFlags()  можно вызвать несколько раз и будет ошибка :) Все, кто будут иметь доступ к Configuration, смогут спарсить флаги. Почему бы код из parse flags не перенести в main и предзаполнить Configuration там? И дальше вызвать метод Init на Configuration ?

2024-08-23 08:11 UTC, alexander-m-utkin commented on internal/pkg/config/config.go
> +	if !c.isInitiated {
Исправил как ты говоришь.

2024-08-23 08:28 UTC, nburunova approved these changes

2024-08-23 08:36 UTC, merged